
/*
 *  This file was generated by the SOM Compiler.
 *  Generated using:
 *     SOM incremental update: 2.43
 */


/*
 *@@sourcefile xfdataf.c:
 *      This file contains SOM code for the following XWorkplace classes:
 *
 *      --  XFldDataFile (WPDataFile replacement)
 *
 *      XFldDataFile is responsible for menu manipulation
 *      and default icon replacements for data files.
 *      Since we should not override WPFileSystem to implement
 *      this functionality for folders and data files altogether,
 *      we must add this to WPDataFile separately.
 *
 *      Installation of this class is now optional (V0.9.0).
 *
 *      Starting with V0.9.0, the files in classes\ contain only
 *      i.e. the methods themselves.
 *      The implementation for this class is mostly in filesys\filesys.c.
 *
 *@@somclass XFldDataFile xfdataf_
 *@@somclass M_XFldDataFile xfdatafM_
 */

/*
 *      Copyright (C) 1997-2000 Ulrich M”ller.
 *      This file is part of the XWorkplace source package.
 *      XWorkplace is free software; you can redistribute it and/or modify
 *      it under the terms of the GNU General Public License as published
 *      by the Free Software Foundation, in version 2 as it comes in the
 *      "COPYING" file of the XWorkplace main distribution.
 *      This program is distributed in the hope that it will be useful,
 *      but WITHOUT ANY WARRANTY; without even the implied warranty of
 *      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *      GNU General Public License for more details.
 */

/*
 *@@todo:
 *
 */

/*
 *  This file was generated by the SOM Compiler and Emitter Framework.
 *  Generated using:
 *      SOM Emitter emitctm: 2.41
 */

#ifndef SOM_Module_xfdataf_Source
#define SOM_Module_xfdataf_Source
#endif
#define XFldDataFile_Class_Source
#define M_XFldDataFile_Class_Source

/*
 *  Suggested #include order:
 *  1)  os2.h
 *  2)  C library headers
 *  3)  setup.h (code generation and debugging options)
 *  4)  headers in helpers\
 *  5)  at least one SOM implementation header (*.ih)
 *  6)  dlgids.h, headers in shared\ (as needed)
 *  7)  headers in implementation dirs (e.g. filesys\, as needed)
 *  8)  #pragma hdrstop and then more SOM headers which crash with precompiled headers
 */

#define INCL_DOSSEMAPHORES
#define INCL_DOSERRORS
#define INCL_WINDIALOGS
#define INCL_WINBUTTONS
#define INCL_WINENTRYFIELDS
#define INCL_WINMENUS
#define INCL_WINMLE
#include <os2.h>

// C library headers
#include <stdio.h>

// generic headers
#include "setup.h"                      // code generation and debugging options

// headers in /helpers
#include "helpers\linklist.h"           // linked list helper routines

// SOM headers which don't crash with prec. header files
#include "xfdataf.ih"

// XWorkplace implementation headers
#include "dlgids.h"                     // all the IDs that are shared with NLS
#include "shared\common.h"              // the majestic XWorkplace include file
#include "shared\kernel.h"              // XWorkplace Kernel
#include "shared\notebook.h"            // generic XWorkplace notebook handling

#include "filesys\filesys.h"            // various file-system object implementation code
#include "filesys\filetype.h"           // extended file types implementation
#include "filesys\menus.h"              // common XFolder context menu logic

// other SOM headers
#pragma hdrstop                 // VAC++ keeps crashing otherwise

/* ******************************************************************
 *                                                                  *
 *   here come the XFldDataFile instance methods                    *
 *                                                                  *
 ********************************************************************/

/*
 *@@ wpInitData:
 *      this instance method gets called when the object
 *      is being initialized. We initialize our instance
 *      data here.
 */

SOM_Scope void  SOMLINK xfdataf_wpInitData(XFldDataFile *somSelf)
{
    XFldDataFileData *somThis = XFldDataFileGetData(somSelf);
    XFldDataFileMethodDebug("XFldDataFile","xfdataf_wpInitData");

    XFldDataFile_parent_WPDataFile_wpInitData(somSelf);

    _pvAssocObjectsList = 0;
    _fAssocObjectsListReady = FALSE;
}

/*
 *@@ wpUnInitData:
 *      free resources allocated by this instance.
 */

SOM_Scope void  SOMLINK xfdataf_wpUnInitData(XFldDataFile *somSelf)
{
    XFldDataFileData *somThis = XFldDataFileGetData(somSelf);
    XFldDataFileMethodDebug("XFldDataFile","xfdataf_wpUnInitData");

    if (_pvAssocObjectsList)
        lstFree(_pvAssocObjectsList);

    XFldDataFile_parent_WPDataFile_wpUnInitData(somSelf);
}

/*
 *@@wpAddFile1Page:
 *      this normally adds the first "File" page to
 *      the file's settings notebook; if allowed,
 *      we will replace this with our own version,
 *      which combines the three "File" pages into
 *      one single page.
 *
 *      XFolder and XFldDataFile share the same
 *      notebook callbacks for this page, since we
 *      have no class replacement for WPFileSystem.
 *
 *@@added V0.9.0 [umoeller]
 */

SOM_Scope ULONG  SOMLINK xfdataf_wpAddFile1Page(XFldDataFile *somSelf,
                                                HWND hwndNotebook)
{
    PCGLOBALSETTINGS pGlobalSettings = cmnQueryGlobalSettings();
    /* XFldDataFileData *somThis = XFldDataFileGetData(somSelf); */
    XFldDataFileMethodDebug("XFldDataFile","xfdataf_wpAddFile1Page");

    if (pGlobalSettings->fReplaceFilePage)
    {
        // page 2
        PCREATENOTEBOOKPAGE pcnbp = malloc(sizeof(CREATENOTEBOOKPAGE));
        PNLSSTRINGS pNLSStrings = cmnQueryNLSStrings();

        memset(pcnbp, 0, sizeof(CREATENOTEBOOKPAGE));
        pcnbp->somSelf = somSelf;
        pcnbp->hwndNotebook = hwndNotebook;
        pcnbp->hmod = cmnQueryNLSModuleHandle(FALSE);
        pcnbp->ulDlgID = ID_XSD_FILESPAGE2;
        pcnbp->ulPageID = SP_FILE2;
        // pcnbp->usPageStyleFlags = BKA_MAJOR;
        pcnbp->pszName = pNLSStrings->pszFilePage;
        pcnbp->fEnumerate = TRUE;
        pcnbp->ulDefaultHelpPanel  = ID_XSH_SETTINGS_FILEPAGE2;

        pcnbp->pfncbInitPage    = (PFNCBACTION)fsysFile2InitPage;
        pcnbp->pfncbItemChanged = (PFNCBITEMCHANGED)fsysFile2ItemChanged;

        ntbInsertPage(pcnbp);

        // page 1
        pcnbp = malloc(sizeof(CREATENOTEBOOKPAGE));
        memset(pcnbp, 0, sizeof(CREATENOTEBOOKPAGE));
        pcnbp->somSelf = somSelf;
        pcnbp->hwndNotebook = hwndNotebook;
        pcnbp->hmod = cmnQueryNLSModuleHandle(FALSE);
        pcnbp->ulDlgID = ID_XSD_FILESPAGE1;
        pcnbp->ulPageID = SP_FILE1;
        pcnbp->usPageStyleFlags = BKA_MAJOR;
        pcnbp->pszName = pNLSStrings->pszFilePage;
        pcnbp->fEnumerate = TRUE;
        pcnbp->ulDefaultHelpPanel  = ID_XSH_SETTINGS_FILEPAGE1;

        pcnbp->pfncbInitPage    = (PFNCBACTION)fsysFile1InitPage;
        pcnbp->pfncbItemChanged = (PFNCBITEMCHANGED)fsysFile1ItemChanged;

        return (ntbInsertPage(pcnbp));
    }
    else
        return (XFldDataFile_parent_WPDataFile_wpAddFile1Page(somSelf,
                                                          hwndNotebook));
}

/*
 *@@wpAddFile2Page:
 *      this normally adds the second "File" page to
 *      the file's settings notebook; since we
 *      combine the three "File" pages into one,
 *      we'll remove this page, if allowed.
 *
 *@@added V0.9.0 [umoeller]
 */

SOM_Scope ULONG  SOMLINK xfdataf_wpAddFile2Page(XFldDataFile *somSelf,
                                                HWND hwndNotebook)
{
    PCGLOBALSETTINGS pGlobalSettings = cmnQueryGlobalSettings();
    /* XFldDataFileData *somThis = XFldDataFileGetData(somSelf); */
    XFldDataFileMethodDebug("XFldDataFile","xfdataf_wpAddFile2Page");

    if (pGlobalSettings->fReplaceFilePage)
        return (SETTINGS_PAGE_REMOVED);
    else
        return (XFldDataFile_parent_WPDataFile_wpAddFile2Page(somSelf,
                                                          hwndNotebook));
}

/*
 *@@wpAddFile3Page:
 *      this normally adds the second "File" page to
 *      the file's settings notebook; since we
 *      combine the three "File" pages into one,
 *      we'll remove this page, if allowed.
 *
 *@@added V0.9.0 [umoeller]
 */

SOM_Scope ULONG  SOMLINK xfdataf_wpAddFile3Page(XFldDataFile *somSelf,
                                                HWND hwndNotebook)
{
    PCGLOBALSETTINGS pGlobalSettings = cmnQueryGlobalSettings();
    /* XFldDataFileData *somThis = XFldDataFileGetData(somSelf); */
    XFldDataFileMethodDebug("XFldDataFile","xfdataf_wpAddFile3Page");

    if (pGlobalSettings->fReplaceFilePage)
        return (SETTINGS_PAGE_REMOVED);
    else
        return (XFldDataFile_parent_WPDataFile_wpAddFile3Page(somSelf,
                                                          hwndNotebook));
}

/*
 *@@ wpFilterPopupMenu:
 *      remove default entries according to Global Settings;
 *      even though XFldObject does this already, we need to
 *      override this for XFldDataFile again, because the
 *      WPS does it too for WPDataFile.
 *
 *      Also we need to do some fiddling with the "Open"
 *      submenu for the extended associations mechanism.
 */

SOM_Scope ULONG  SOMLINK xfdataf_wpFilterPopupMenu(XFldDataFile *somSelf,
                                                   ULONG ulFlags,
                                                   HWND hwndCnr,
                                                   BOOL fMultiSelect)
{
    ULONG ulMenuFilter = 0;
    PCGLOBALSETTINGS pGlobalSettings = cmnQueryGlobalSettings();
    /* XFldDataFileData *somThis = XFldDataFileGetData(somSelf); */
    XFldDataFileMethodDebug("XFldDataFile","xfdataf_wpFilterPopupMenu");

    ulMenuFilter = XFldDataFile_parent_WPDataFile_wpFilterPopupMenu(somSelf,
                                                                    ulFlags,
                                                                    hwndCnr,
                                                                    fMultiSelect);

    // now suppress default menu items according to
    // Global Settings;
    // the DefaultMenuItems field in pGlobalSettings is
    // ready-made for this function; the "Workplace Shell"
    // notebook page for removing menu items sets this field with
    // the proper CTXT_xxx flags
    ulMenuFilter &= ~pGlobalSettings->DefaultMenuItems;

    /* if (pGlobalSettings->fExtAssocs)
        // if extended associations are on, we MUST remove
        // the "Open" submenu as well, because there's no
        // other &%$õ%&% way to get rid of the WPS associations
        // otherwise... this is REALLY sick!
        ulMenuFilter &= ~CTXT_OPEN;
        // we will re-add the "Open" menu in
        // mnuModifyDataFilePopupMenu again
    */

    return (ulMenuFilter);
}

/*
 *@@ wpModifyPopupMenu:
 *      add datafile object popup menu entries.
 *
 *      We don't need a wpMenuItemSelected method override
 *      for data  files, because the new menu items are
 *      completely handled by the subclassed folder frame
 *      window procedure by calling the functions in menus.c.
 */

SOM_Scope BOOL  SOMLINK xfdataf_wpModifyPopupMenu(XFldDataFile *somSelf,
                                                  HWND hwndMenu,
                                                  HWND hwndCnr,
                                                  ULONG iPosition)
{
    BOOL brc = TRUE;

    /* somId MethodId = somIdFromString("wpModifyPopupMenu");
    SOMClassMgr *cm = somEnvironmentNew();

    // somTD_WPObject_wpModifyPopupMenu XFldDataFile_parent_WPFileSystem_wpModifyPopupmenu = 0;

    somTD_WPObject_wpModifyPopupMenu
        XFldDataFile_parent_WPFileSystem_wpModifyPopupmenu
        = (somTD_WPObject_wpModifyPopupMenu)
              _somLookupMethod(_WPObject, MethodId);

    SOMFree(MethodId); */

    /* XFldDataFileData *somThis = XFldDataFileGetData(somSelf); */
    XFldDataFileMethodDebug("XFldDataFile","xfdataf_wpModifyPopupMenu");

    brc = XFldDataFile_parent_WPDataFile_wpModifyPopupMenu(somSelf,
                                                           hwndMenu,
                                                           hwndCnr,
                                                           iPosition);

    if (brc)
        // manipulate the data file menu according to our needs
        brc = mnuModifyDataFilePopupMenu(somSelf, hwndMenu, hwndCnr, iPosition);

    return (brc);
}

/*
 *@@ wpDisplayMenu:
 *      this WPObject instance method creates and displays
 *      an object's popup menu, which is returned.
 *
 *      From my testing (after overriding _all_ WPDataFile methods...),
 *      I found out that wpDisplayMenu calls the following methods
 *      in this order:
 *
 *      --  wpFilterMenu (Warp-4-specific);
 *      --  wpFilterPopupMenu;
 *      --  wpModifyPopupMenu;
 *      --  wpModifyMenu (Warp-4-specific).
 *
 *      Normally, this method does not need to be overridden
 *      to modify menus. HOWEVER, with Warp 4, IBM was kind
 *      enough to ignore all changes to the list of associated
 *      programs added to the "Open" submenu, because most
 *      apparently, Warp 4 no longer adds the programs in
 *      the wpModifyPopupMenu method, but in the Warp-4-specific
 *      wpModifyMenu method, which is called too late for me.
 *
 *      Unfortunately, it is thus impossible to prevent the WPS
 *      from adding program objects to the "Open" submenu, except
 *      for overriding this method and removing them all again, or
 *      breaking compatibility with Warp 3. Duh.
 *
 *      So for data files, after the menu has been completely
 *      built (in the parent method, which in turn calls
 *      wpModifyMenu), we call ftypModifyDataFileOpenSubmenu.
 *
 *@@added V0.9.0 [umoeller]
 */

SOM_Scope HWND  SOMLINK xfdataf_wpDisplayMenu(XFldDataFile *somSelf,
                                              HWND hwndOwner,
                                              HWND hwndClient,
                                              POINTL* ptlPopupPt,
                                              ULONG ulMenuType,
                                              ULONG ulReserved)
{
    HWND hwndMenu = 0;

    PCGLOBALSETTINGS pGlobalSettings = cmnQueryGlobalSettings();
    // XFldDataFileData *somThis = XFldDataFileGetData(somSelf);
    XFldDataFileMethodDebug("XFldDataFile","xfdataf_wpDisplayMenu");

    hwndMenu = XFldDataFile_parent_WPDataFile_wpDisplayMenu(somSelf,
                                                            hwndOwner,
                                                            hwndClient,
                                                            ptlPopupPt,
                                                            ulMenuType,
                                                            ulReserved);

    if (pGlobalSettings->fExtAssocs)
    {
        ftypModifyDataFileOpenSubmenu(somSelf,
                                      hwndMenu);
    }

    return (hwndMenu);
}

/*
 *@@ wpMenuItemHelpSelected:
 *      display help for a context menu item.
 */

SOM_Scope BOOL  SOMLINK xfdataf_wpMenuItemHelpSelected(XFldDataFile *somSelf,
                                                       ULONG MenuId)
{
    /* XFldDataFileData *somThis = XFldDataFileGetData(somSelf); */
    XFldDataFileMethodDebug("XFldDataFile","xfdataf_wpMenuItemHelpSelected");

    // call the common help processor in menus.c;
    if (mnuMenuItemHelpSelected(somSelf, MenuId))
        // if this returns TRUE, help was requested for one
        // of the new menu items
        return TRUE;
    else
        // else: none of our menu items, call default
        return (XFldDataFile_parent_WPDataFile_wpMenuItemHelpSelected(somSelf,
                                                                 MenuId));
}

/*
 *@@ wpQueryAssociatedFileIcon:
 *      this method should return the icon of the associated
 *      program (file) object.
 *
 *      From what I see, this only gets called while a folder
 *      is being populated (in order to find out the correct
 *      data file icon), but not when a context menu is opened.
 *
 *      The default version of this method calls
 *      XFldDataFile::wpQueryAssociatedProgram.
 *
 *@@added V0.9.0 [umoeller]
 */

SOM_Scope HPOINTER  SOMLINK xfdataf_wpQueryAssociatedFileIcon(XFldDataFile *somSelf)
{
    HPOINTER hp = 0;
    /* XFldDataFileData *somThis = XFldDataFileGetData(somSelf); */
    // XFldDataFileMethodDebug("XFldDataFile","xfdataf_wpQueryAssociatedFileIcon");

    #if defined DEBUG_ASSOCS || defined DEBUG_SOMMETHODS
        _Pmpf(("Entering wpQueryAssociatedFileIcon for %s", _wpQueryTitle(somSelf)));
    #endif

    hp =  XFldDataFile_parent_WPDataFile_wpQueryAssociatedFileIcon(somSelf);

    #if defined DEBUG_ASSOCS || defined DEBUG_SOMMETHODS
        _Pmpf(("End of wpQueryAssociatedFileIcon for %s", _wpQueryTitle(somSelf)));
    #endif

    return (hp);
}

/*
 *@@ wpQueryAssociatedProgram:
 *      this method returns the associated WPProgram or
 *      WPProgramFile object for a data file.
 *
 *      Per default, this gets called from
 *      XFldDataFile::wpQueryAssociatedFileIcon -- that
 *      is, only while a folder is being populated, but
 *      _not_ when a context menu is opened. There seems
 *      to be a second association mechanism in wpModifyPopupMenu
 *      somewhere to add all the associated programs to
 *      the "Open" submenu. I have tested this by returning
 *      NULL in this method, and all the program objects
 *      still appear in the "Open" menu -- it's just the
 *      data file icons which get set to the default icon
 *      then.
 *
 *      The WPS docs say that this should be overridden
 *      to introduce new association mechanisms.
 *
 *      From what I see, ulView is normally 0x1000, which
 *      is the WPS-internal code for the first associated
 *      program. This is only > 1000 if the default
 *      association has been changed on the "Menu" page
 *      of a data file (1001 for the second assoc, 1002
 *      for the third, etc.).
 *
 *      This returns NULL if there's no associated program
 *      for the specified view.
 *
 *@@added V0.9.0 [umoeller]
 */

SOM_Scope WPObject*  SOMLINK xfdataf_wpQueryAssociatedProgram(XFldDataFile *somSelf,
                                                              ULONG ulView,
                                                              PULONG pulHowMatched,
                                                              PSZ pszMatchString,
                                                              ULONG cbMatchString,
                                                              PSZ pszDefaultType)
{
    WPObject* pobj = 0;
    PCGLOBALSETTINGS pGlobalSettings = cmnQueryGlobalSettings();

    /* XFldDataFileData *somThis = XFldDataFileGetData(somSelf); */
    // XFldDataFileMethodDebug("XFldDataFile","xfdataf_wpQueryAssociatedProgram");

    #if defined DEBUG_ASSOCS || defined DEBUG_SOMMETHODS
        _Pmpf(("Entering wpQueryAssociatedProgram for %s; ulView = %lX, "
               "*pulHowMatched = 0x%lX, "
               "pszMatchString = %s, pszDefaultType = %s",
               _wpQueryTitle(somSelf),
               ulView,
               (    (pulHowMatched)
                            ? (*pulHowMatched)
                            : 0
               ),
               pszMatchString, pszDefaultType
               ));
    #endif

    if (pGlobalSettings->fExtAssocs)
        // "extended associations" allowed:
        // use our replacement mechanism
        pobj = ftypQueryAssociatedProgram(somSelf,
                                          ulView,
                                          pulHowMatched,
                                          pszMatchString,
                                          cbMatchString,
                                          pszDefaultType);
    else
        pobj = XFldDataFile_parent_WPDataFile_wpQueryAssociatedProgram(somSelf,
                                                                       ulView,
                                                                       pulHowMatched,
                                                                       pszMatchString,
                                                                       cbMatchString,
                                                                       pszDefaultType);

    #if defined DEBUG_ASSOCS || defined DEBUG_SOMMETHODS
        _Pmpf(("End of wpQueryAssociatedProgram for %s", _wpQueryTitle(somSelf)));
    #endif

    return (pobj);
}

/*
 *@@ wpSetAssociatedFileIcon:
 *      this method gets called by the WPS when a data
 *      file object is being initialized, to have it
 *      set its icon to that of the default association.
 *
 *      From what I see, this method only seems to be called
 *      when a Settings view is _opened_, not when it's closed,
 *      which doesn't really make sense.
 *
 *@@added V0.9.0 [umoeller]
 */

SOM_Scope void  SOMLINK xfdataf_wpSetAssociatedFileIcon(XFldDataFile *somSelf)
{
    /* XFldDataFileData *somThis = XFldDataFileGetData(somSelf); */
    XFldDataFileMethodDebug("XFldDataFile","xfdataf_wpSetAssociatedFileIcon");

    // _Pmpf(("Entering wpSetAssociatedFileIcon for %s", _wpQueryTitle(somSelf)));
    XFldDataFile_parent_WPDataFile_wpSetAssociatedFileIcon(somSelf);
    // _Pmpf(("End of wpSetAssociatedFileIcon for %s", _wpQueryTitle(somSelf)));
}


/* ******************************************************************
 *                                                                  *
 *   here come the XFldDataFile class methods                       *
 *                                                                  *
 ********************************************************************/

/*
 *@@ wpclsInitData:
 *      initialize XFldDataFile class data.
 *
 *@@changed V0.9.0 [umoeller]: added class object to KERNELGLOBALS
 */

SOM_Scope void  SOMLINK xfdatafM_wpclsInitData(M_XFldDataFile *somSelf)
{
    // M_XFldDataFileData *somThis = M_XFldDataFileGetData(somSelf);
    M_XFldDataFileMethodDebug("M_XFldDataFile","xfdatafM_wpclsInitData");

    M_XFldDataFile_parent_M_WPDataFile_wpclsInitData(somSelf);

    {
        PKERNELGLOBALS   pKernelGlobals = krnLockGlobals(5000);
        // store the class object in KERNELGLOBALS
        pKernelGlobals->fXFldDataFile = TRUE;
        krnUnlockGlobals();
    }
}

/*
 *@@ wpclsCreateDefaultTemplates:
 *      this is called by the system to allow a class to
 *      create its default templates. The default WPS
 *      behavior is to create new templates if the class
 *      default title is different from the existing
 *      templates, but since we are replacing the class,
 *      we will have to suppress this in order not to
 *      crowd the Templates folder.
 */

SOM_Scope BOOL  SOMLINK xfdatafM_wpclsCreateDefaultTemplates(M_XFldDataFile *somSelf,
                                                             WPObject* Folder)
{
    // M_XFldDataFileData *somThis = M_XFldDataFileGetData(somSelf);
    M_XFldDataFileMethodDebug("M_XFldDataFile","xfdatafM_wpclsCreateDefaultTemplates");

    // we only override this class method if it is
    // being called for the XFolder class object itself.
    // If this is being called for a subclass, we use
    // the parent method, because we do not want to
    // break the default behavior for subclasses.
    // this is not working on Warp 3
    if (somSelf == _XFldDataFile)
        return (TRUE);
        // means that the Templates folder should _not_ create templates
        // by itself; we pretend that we've done this
    else
        return (M_XFldDataFile_parent_M_WPDataFile_wpclsCreateDefaultTemplates(somSelf,
                                                                           Folder));

}

/*
 *@@ wpclsQueryIconData:
 *      give data files a new default icon, if the
 *      global settings allow this.
 *      This is loaded from /ICONS/ICONS.DLL.
 */

SOM_Scope ULONG  SOMLINK xfdatafM_wpclsQueryIconData(M_XFldDataFile *somSelf,
                                                     PICONINFO pIconInfo)
{
    ULONG       ulrc;
    HMODULE     hmodIconsDLL = NULLHANDLE;
    PCGLOBALSETTINGS pGlobalSettings = cmnQueryGlobalSettings();
    // M_XFldDataFileData *somThis = M_XFldDataFileGetData(somSelf);
    M_XFldDataFileMethodDebug("M_XFldDataFile","xfdatafM_wpclsQueryIconData");

    if (pGlobalSettings->fReplaceIcons)
    {
        hmodIconsDLL = cmnQueryIconsDLL();
        // icon replacements allowed:
        if ((pIconInfo) && (hmodIconsDLL))
        {
            pIconInfo->fFormat = ICON_RESOURCE;
            pIconInfo->hmod = hmodIconsDLL;
            pIconInfo->resid = 109;
        }
        ulrc = sizeof(ICONINFO);
    }

    if (hmodIconsDLL == NULLHANDLE)
        // icon replacements not allowed: call default
        ulrc = M_XFldDataFile_parent_M_WPDataFile_wpclsQueryIconData(somSelf,
                                                                  pIconInfo);

    return (ulrc);
}

