
/*
 *@@sourcefile xfwps.c:
 *      This file contains SOM code for the following XWorkplace classes:
 *
 *      --  XFldWPS SOM stuff (WPSystem subclass)
 *
 *      This class implements the "Workplace Shell" settings
 *      object.
 *
 *      Installation of this class is optional, but you won't
 *      be able to change XWorkplace's settings without it.
 *
 *      This class used to be in xfsys.c (together with XFldSystem,
 *      the "OS/2 Kernel" object), but has been moved here for
 *      clarity with V0.9.0.
 *
 *      Starting with V0.9.0, the files in classes\ contain only
 *      i.e. the methods themselves.
 *      The implementation for this class is in several files in
 *      filesys\; check the function prefixes to find out where.
 *
 *@@somclass XFldWPS xfwps_
 *@@somclass M_XFldWPS xfwpsM_
 */

/*
 *      Copyright (C) 1997-2002 Ulrich M”ller.
 *      This file is part of the XWorkplace source package.
 *      XWorkplace is free software; you can redistribute it and/or modify
 *      it under the terms of the GNU General Public License as published
 *      by the Free Software Foundation, in version 2 as it comes in the
 *      "COPYING" file of the XWorkplace main distribution.
 *      This program is distributed in the hope that it will be useful,
 *      but WITHOUT ANY WARRANTY; without even the implied warranty of
 *      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *      GNU General Public License for more details.
 */

/*
 *  This file was generated by the SOM Compiler and Emitter Framework.
 *  Generated using:
 *      SOM Emitter emitctm: 2.41
 */

#ifndef SOM_Module_xfwps_Source
#define SOM_Module_xfwps_Source
#endif
#define xfwps_Class_Source
#define M_xfwps_Class_Source

#pragma strings(readonly)

/*
 *  Suggested #include order:
 *  1)  os2.h
 *  2)  C library headers
 *  3)  setup.h (code generation and debugging options)
 *  4)  headers in helpers\
 *  5)  at least one SOM implementation header (*.ih)
 *  6)  dlgids.h, headers in shared\ (as needed)
 *  7)  headers in implementation dirs (e.g. filesys\, as needed)
 *  8)  #pragma hdrstop and then more SOM headers which crash with precompiled headers
 */

#define INCL_DOSSEMAPHORES
#define INCL_WINMENUS
#include <os2.h>

// C library headers
#include <stdio.h>              // needed for except.h

// generic headers
#include "setup.h"                      // code generation and debugging options

// headers in /helpers
#include "helpers\dosh.h"               // Control Program helper routines

// SOM headers which don't crash with prec. header files
#include "xfwps.ih"
#include "xfldr.ih"

// XWorkplace implementation headers
#include "dlgids.h"                     // all the IDs that are shared with NLS
#include "shared\common.h"              // the majestic XWorkplace include file
#include "shared\helppanels.h"          // all XWorkplace help panel IDs
#include "shared\kernel.h"              // XWorkplace Kernel
#include "shared\notebook.h"            // generic XWorkplace notebook handling

#include "filesys\filetype.h"           // extended file types implementation
#include "filesys\folder.h"             // XFolder implementation
#include "filesys\fdrmenus.h"           // shared folder menu logic
#include "filesys\statbars.h"           // status bar translation logic

// other SOM headers
#pragma hdrstop                         // VAC++ keeps crashing otherwise

/* ******************************************************************
 *                                                                  *
 *   here come the XFldWPS instance methods                         *
 *                                                                  *
 ********************************************************************/

/*
 *@@ xwpAddWPSMenuPages:
 *
 *@@added V0.9.16 (2001-10-08) [umoeller]
 *@@changed V0.9.16 (2001-10-23) [umoeller]: fixed page subtitles
 */

SOM_Scope ULONG  SOMLINK xfwps_xwpAddWPSMenuPages(XFldWPS *somSelf,
                                                  HWND hwndDlg)
{
    INSERTNOTEBOOKPAGE inbp;
    HMODULE         savehmod = cmnQueryNLSModuleHandle(FALSE);

    XFldWPSMethodDebug("XFldWPS","xfwps_xwpAddWPSMenuPages");

    /*
     * "Menu items" pages
     */

    memset(&inbp, 0, sizeof(INSERTNOTEBOOKPAGE));
    inbp.somSelf = somSelf;
    inbp.hwndNotebook = hwndDlg;
    inbp.hmod = savehmod;
    inbp.usPageStyleFlags = BKA_MINOR;
    inbp.fEnumerate = TRUE;
    inbp.pcszName = cmnGetString(ID_XSSI_2REMOVEITEMS);  // psz2RemoveItems
    inbp.ulDlgID = ID_XSD_SET2REMOVEMENUS;
    // inbp.usFirstControlID = ID_XSDI_FIND;
    // inbp.ulFirstSubpanel = ID_XSH_SETTINGS_REMOVEMENUS_SUB;        // help panel for "Find"
    inbp.ulDefaultHelpPanel  = ID_XSH_SETTINGS_REMOVEMENUS;
    inbp.ulPageID = SP_2REMOVEITEMS;
    inbp.pfncbInitPage    = mnuRemoveMenusInitPage;
    inbp.pfncbItemChanged = mnuRemoveMenusItemChanged;
    ntbInsertPage(&inbp);

    // insert "Config folder menu items" page
    memset(&inbp, 0, sizeof(INSERTNOTEBOOKPAGE));
    inbp.somSelf = somSelf;
    inbp.hwndNotebook = hwndDlg;
    inbp.hmod = savehmod;
    inbp.usPageStyleFlags = BKA_MINOR;
    inbp.fEnumerate = TRUE;
    inbp.pcszName = cmnGetString(ID_XSSI_26CONFIGITEMS);  // psz26ConfigFolderMenus
    inbp.ulDlgID = ID_XSD_SET26CONFIGMENUS;
    // inbp.usFirstControlID = ID_XSDI_CASCADE;
    // inbp.ulFirstSubpanel = ID_XSH_SETTINGS_CFGM_SUB;       // help panel for "Cascade..."
    inbp.ulDefaultHelpPanel  = ID_XSH_SETTINGS_CFGM;
    inbp.ulPageID = SP_26CONFIGITEMS;
    inbp.pfncbInitPage    = mnuConfigFolderMenusInitPage;
    inbp.pfncbItemChanged = mnuConfigFolderMenusItemChanged;
    ntbInsertPage(&inbp);

    // insert "Add Menu Items" page
    memset(&inbp, 0, sizeof(INSERTNOTEBOOKPAGE));
    inbp.somSelf = somSelf;
    inbp.hwndNotebook = hwndDlg;
    inbp.hmod = savehmod;
    inbp.usPageStyleFlags = BKA_MAJOR;
    inbp.fEnumerate = TRUE;
    inbp.pcszName
    = inbp.pcszMinorName              // V0.9.16 (2001-10-23) [umoeller]
    = cmnGetString(ID_XSSI_25ADDITEMS);  // psz25AddItems
    // inbp.ulDlgID = ID_XSD_SET25ADDMENUS;
    inbp.ulDlgID = ID_XFD_EMPTYDLG;           // V0.9.16 (2001-09-29) [umoeller]
    // inbp.usFirstControlID = ID_XSDI_FILEATTRIBS;
    // inbp.ulFirstSubpanel = ID_XSH_SETTINGS_ADDMENUS_SUB;   // help panel for "Add file attribs"
    inbp.ulDefaultHelpPanel  = ID_XSH_SETTINGS_ADDMENUS;
    inbp.ulPageID = SP_25ADDITEMS;
    inbp.pfncbInitPage    = mnuAddMenusInitPage;
    inbp.pfncbItemChanged = mnuAddMenusItemChanged;
    return (ntbInsertPage(&inbp));
}

/*
 *@@ xwpAddXFldWPSPages:
 *      this actually adds the XWorkplace pages into the
 *      "Workplace Shell" notebook.
 *
 *@@changed V0.9.0 [umoeller]: added "File types" page, removed "XFolder" pages
 *@@changed V0.9.6 (2000-10-16) [umoeller]: made "File types" resizeable
 */

SOM_Scope ULONG  SOMLINK xfwps_xwpAddXFldWPSPages(XFldWPS *somSelf,
                                                 HWND hwndDlg)
{
    INSERTNOTEBOOKPAGE inbp;
    HMODULE         savehmod = cmnQueryNLSModuleHandle(FALSE);
    // PCGLOBALSETTINGS pGlobalSettings = cmnQueryGlobalSettings();
    // XFldWPSData *somThis = XFldWPSGetData(somSelf);
    XFldWPSMethodDebug("XFldWPS","xfwps_xwpAddXFldWPSPages");

    // insert "Sort" page
#ifndef __ALWAYSEXTSORT__
    if (cmnQuerySetting(sfExtendedSorting))
#endif
    {
        // extended sorting enabled:
        memset(&inbp, 0, sizeof(INSERTNOTEBOOKPAGE));
        inbp.somSelf = somSelf;
        inbp.hwndNotebook = hwndDlg;
        inbp.hmod = savehmod;
        inbp.ulDlgID = ID_XSD_SETTINGS_FLDRSORT;
        inbp.usPageStyleFlags = BKA_MAJOR;
        inbp.pcszName = cmnGetString(ID_XSSI_SORT);  // pszSort
        inbp.ulDefaultHelpPanel  = ID_XSH_SORTPAGE;
                        // changed V0.9.12 (2001-05-20) [umoeller]

        // mark this page as "global", because both
        // the instance settings notebook and the
        // "Workplace Shell" object use the same
        // callbacks
        inbp.ulPageID = SP_FLDRSORT_GLOBAL;
        inbp.pfncbInitPage    = fdrSortInitPage;
        inbp.pfncbItemChanged = fdrSortItemChanged;
        ntbInsertPage(&inbp);
    }

    // insert "Hotkeys" page
#ifndef __ALWAYSFDRHOTKEYS__
    if (cmnQuerySetting(sfFolderHotkeys))
#endif
    {
        memset(&inbp, 0, sizeof(INSERTNOTEBOOKPAGE));
        inbp.somSelf = somSelf;
        inbp.hwndNotebook = hwndDlg;
        inbp.hmod = savehmod;
        inbp.ulDlgID = ID_XSD_SET4ACCELS;
        inbp.usPageStyleFlags = BKA_MAJOR;
        inbp.pcszName = cmnGetString(ID_XSSI_4ACCELERATORS);  // psz4Accelerators
        inbp.ulDefaultHelpPanel  = ID_XSH_SETTINGS1+5;
        inbp.ulPageID = SP_4ACCELERATORS;
        inbp.pfncbInitPage    = fdrHotkeysInitPage;
        inbp.pfncbItemChanged = fdrHotkeysItemChanged;
        ntbInsertPage(&inbp);
    }

    // insert "Snap to grid" page
#ifndef __NOSNAPTOGRID__
    if (cmnQuerySetting(sfSnap2Grid))
    {
        memset(&inbp, 0, sizeof(INSERTNOTEBOOKPAGE));
        inbp.somSelf = somSelf;
        inbp.hwndNotebook = hwndDlg;
        inbp.hmod = savehmod;
        inbp.usPageStyleFlags = BKA_MAJOR;
        inbp.pcszName = cmnGetString(ID_XSSI_3SNAPTOGRID);  // psz3SnapToGrid
        inbp.ulDlgID = ID_XSD_SET3SNAPTOGRID;
        inbp.ulDefaultHelpPanel  = ID_XSH_SETTINGS1+4;
        inbp.ulPageID = SP_3SNAPTOGRID;
        inbp.pfncbInitPage    = fdrGridInitPage;
        inbp.pfncbItemChanged = fdrGridItemChanged;
        ntbInsertPage(&inbp);
    }
#endif

    /*
     * "Status bar" pages
     */

    if (
#ifndef __ALWAYSSUBCLASS__
            (!cmnQuerySetting(sfNoSubclassing))
#else
        1
#endif
        &&
#ifndef __NOCFGSTATUSBARS__
            (cmnQuerySetting(sfStatusBars))
#else
        1
#endif
       )
    {
#ifndef __NOCFGSTATUSBARS__
        // insert "Status bar" page 2
        memset(&inbp, 0, sizeof(INSERTNOTEBOOKPAGE));
        inbp.somSelf = somSelf;
        inbp.hwndNotebook = hwndDlg;
        inbp.hmod = savehmod;
        inbp.usPageStyleFlags = BKA_MINOR;
        inbp.fEnumerate = TRUE;
        // inbp.pcszName = cmnGetString(ID_XSSI_27STATUSBAR);  // psz27StatusBar
            // this is page 2, don't give it a title (context menu)
            // V0.9.16 (2001-10-23) [umoeller]
        inbp.ulDlgID = ID_XSD_SET28STATUSBARS2;
        inbp.ulDefaultHelpPanel  = ID_XSH_SETTINGS_SB2;
        inbp.ulPageID = SP_28STATUSBAR2;
        inbp.pfncbInitPage    = stbStatusBar2InitPage;
        inbp.pfncbItemChanged = stbStatusBar2ItemChanged;
        ntbInsertPage(&inbp);
#endif

        // insert "Status bar" page 1
        memset(&inbp, 0, sizeof(INSERTNOTEBOOKPAGE));
        inbp.somSelf = somSelf;
        inbp.hwndNotebook = hwndDlg;
        inbp.hmod = savehmod;
        inbp.usPageStyleFlags = BKA_MAJOR;
        inbp.fEnumerate = TRUE;
        inbp.pcszName = cmnGetString(ID_XSSI_27STATUSBAR);  // psz27StatusBar
        inbp.ulDlgID = ID_XSD_SET27STATUSBARS;
        inbp.ulDefaultHelpPanel  = ID_XSH_SETTINGS1+3;
        inbp.ulPageID = SP_27STATUSBAR;
        inbp.pfncbInitPage    = stbStatusBar1InitPage;
        inbp.pfncbItemChanged = stbStatusBar1ItemChanged;
        ntbInsertPage(&inbp);
    }

    /*
     * "View" page (XFolder)
     */

    memset(&inbp, 0, sizeof(INSERTNOTEBOOKPAGE));
    inbp.somSelf = somSelf;
    inbp.hwndNotebook = hwndDlg;
    inbp.hmod = savehmod;
    inbp.usPageStyleFlags = BKA_MAJOR;
    inbp.fEnumerate = TRUE;
    inbp.pcszName = cmnGetString(ID_XSSI_WPSFDRVIEWPAGE);  // V0.9.16(2001-11-04) [umoeller]
    // inbp.ulDlgID = ID_XSD_FOLDERVIEWS;
    inbp.ulDlgID = ID_XFD_EMPTYDLG;           // V0.9.16 (2001-09-29) [umoeller]
    inbp.ulDefaultHelpPanel  = ID_XSH_SETTINGS1;
    inbp.ulPageID = SP_1GENERIC;
    inbp.pfncbInitPage    = fdrViewInitPage;
    inbp.pfncbItemChanged = fdrViewItemChanged;
    ntbInsertPage(&inbp);

    // moved menu pages before "View" page
    // V0.9.16(2001-11-04) [umoeller]
    _xwpAddWPSMenuPages(somSelf, hwndDlg);

    /*
     * "File types" page (new with V0.9.0)
     */

#ifndef __NEVEREXTASSOCS__
    if (cmnQuerySetting(sfExtAssocs))
    {
        memset(&inbp, 0, sizeof(INSERTNOTEBOOKPAGE));
        inbp.somSelf = somSelf;
        inbp.hwndNotebook = hwndDlg;
        inbp.hmod = savehmod;
        inbp.usPageStyleFlags = BKA_MAJOR;
        inbp.pcszName = cmnGetString(ID_XSSI_FILETYPESPAGE);  // pszFileTypesPage
        inbp.ulDlgID = ID_XSD_FILETYPES;
        inbp.ulDefaultHelpPanel  = ID_XSH_SETTINGS_FILETYPES;
        inbp.ulPageID = SP_FILETYPES;
        inbp.pampControlFlags = G_pampFileTypesPage;
        inbp.cControlFlags = G_cFileTypesPage;
        inbp.pfncbInitPage    = ftypFileTypesInitPage;
        inbp.pfncbItemChanged = ftypFileTypesItemChanged;
        ntbInsertPage(&inbp);
    }
#endif

    return (TRUE);
}

/*
 *@@ wpFilterPopupMenu:
 *      this WPObject instance method allows the object to
 *      filter out unwanted menu items from the context menu.
 *      This gets called before wpModifyPopupMenu.
 *
 *      We remove the "Create another" menu item.
 *
 *@@added V0.9.2 (2000-02-26) [umoeller]
 */

SOM_Scope ULONG  SOMLINK xfwps_wpFilterPopupMenu(XFldWPS *somSelf,
                                                 ULONG ulFlags,
                                                 HWND hwndCnr,
                                                 BOOL fMultiSelect)
{
    /* XFldWPSData *somThis = XFldWPSGetData(somSelf); */
    XFldWPSMethodDebug("XFldWPS","xfwps_wpFilterPopupMenu");

    return (XFldWPS_parent_WPSystem_wpFilterPopupMenu(somSelf,
                                                      ulFlags,
                                                      hwndCnr,
                                                      fMultiSelect)
            & ~CTXT_NEW
           );
}

/*
 *@@ wpQueryDefaultHelp:
 *      this WPObject instance method specifies the default
 *      help panel for an object (when "Extended help" is
 *      selected from the object's context menu). This should
 *      describe what this object can do in general.
 *      We must return TRUE to report successful completion.
 *
 *      We will display some introduction to "Workplace Shell".
 *
 *@@added V0.9.0 [umoeller]
 */

SOM_Scope BOOL  SOMLINK xfwps_wpQueryDefaultHelp(XFldWPS *somSelf,
                                                 PULONG pHelpPanelId,
                                                 PSZ HelpLibrary)
{
    /* XFldWPSData *somThis = XFldWPSGetData(somSelf); */
    XFldWPSMethodDebug("XFldWPS","xfwps_wpQueryDefaultHelp");

    strcpy(HelpLibrary, cmnQueryHelpLibrary());
    *pHelpPanelId = ID_XSH_XFLDWPS;
    return (TRUE);
}

/*
 *@@ wpAddSystemScreenPage:
 *      this WPSystem instance method is overridden in order
 *      to suppress the "Screen" page in the "Workplace Shell"
 *      object, because we want that page in the new "Screen"
 *      object instead.
 */

SOM_Scope ULONG  SOMLINK xfwps_wpAddSystemScreenPage(XFldWPS *somSelf,
                                                     HWND hwndNotebook)
{
    /* XFldWPSData *somThis = XFldWPSGetData(somSelf); */
    XFldWPSMethodDebug("XFldWPS","xfwps_wpAddSystemScreenPage");

    return (SETTINGS_PAGE_REMOVED);
}

/*
 *@@ wpAddDMQSDisplayTypePage:
 *      this WPSystem instance method is overridden in order
 *      to suppress the second "Screen" page in the "Workplace
 *      Shell" object. Depending on the installed video driver,
 *      this page may or may not be displayed in the "System"
 *      notebook, but we never want this in "Workplace Shell",
 *      but in "Screen" instead.
 */

SOM_Scope ULONG  SOMLINK xfwps_wpAddDMQSDisplayTypePage(XFldWPS *somSelf,
                                                        HWND hwndNotebook)
{
    /* XFldWPSData *somThis = XFldWPSGetData(somSelf); */
    XFldWPSMethodDebug("XFldWPS","xfwps_wpAddDMQSDisplayTypePage");

    return (SETTINGS_PAGE_REMOVED);
}

/*
 *@@ wpAddSystemPrintScreenPage:
 *      this WPSystem instance method is overridden in order
 *      to suppress the "Print screen" page in the "Workplace
 *      Shell" object. We want this page in the new "Screen"
 *      object instead.
 *
 *@@added V0.9.2 (2000-02-23) [umoeller]
 */

SOM_Scope ULONG  SOMLINK xfwps_wpAddSystemPrintScreenPage(XFldWPS *somSelf,
                                                          HWND hwndNotebook)
{
    /* XFldWPSData *somThis = XFldWPSGetData(somSelf); */
    XFldWPSMethodDebug("XFldWPS","xfwps_wpAddSystemPrintScreenPage");

    return (SETTINGS_PAGE_REMOVED);
}

/*
 *@@ wpAddSettingsPages:
 *      this WPObject instance method gets called by the WPS
 *      when the Settings view is opened to have all the
 *      settings page inserted into hwndNotebook.
 *
 *      We add the new XWorkplace pages on top of
 *      the other WPS settings pages from the old "System"
 *      notebook.
 */

SOM_Scope BOOL  SOMLINK xfwps_wpAddSettingsPages(XFldWPS *somSelf,
                                                 HWND hwndNotebook)
{
    /* XFldWPSData *somThis = XFldWPSGetData(somSelf); */
    XFldWPSMethodDebug("XFldWPS","xfwps_wpAddSettingsPages");

    XFldWPS_parent_WPSystem_wpAddSettingsPages(somSelf,
                                               hwndNotebook);

    // add XFolder pages on top
    _xwpAddXFldWPSPages(somSelf, hwndNotebook);

    return (TRUE);
}

/*
 *@@ wpclsInitData:
 *      this WPObject class method gets called when a class
 *      is loaded by the WPS (probably from within a
 *      somFindClass call) and allows the class to initialize
 *      itself.
 *
 *@@changed V0.9.0 [umoeller]: added class object to KERNELGLOBALS
 */

SOM_Scope void  SOMLINK xfwpsM_wpclsInitData(M_XFldWPS *somSelf)
{
    /* M_XFldWPSData *somThis = M_XFldWPSGetData(somSelf); */
    M_XFldWPSMethodDebug("M_XFldWPS","xfwpsM_wpclsInitData");

    M_XFldWPS_parent_M_WPSystem_wpclsInitData(somSelf);

    krnClassInitialized(G_pcszXFldWPS);
}

/* ******************************************************************
 *                                                                  *
 *   here come the XFldWPS class methods                            *
 *                                                                  *
 ********************************************************************/

/*
 *@@ wpclsQuerySettingsPageSize:
 *      this WPObject class method should return the
 *      size of the largest settings page in dialog
 *      units; if a settings notebook is initially
 *      opened, i.e. no window pos has been stored
 *      yet, the WPS will use this size, to avoid
 *      truncated settings pages.
 */

SOM_Scope BOOL  SOMLINK xfwpsM_wpclsQuerySettingsPageSize(M_XFldWPS *somSelf,
                                                          PSIZEL pSizl)
{
    BOOL brc;
    /* M_XFldWPSData *somThis = M_XFldWPSGetData(somSelf); */
    M_XFldWPSMethodDebug("M_XFldWPS","xfwpsM_wpclsQuerySettingsPageSize");

    brc = M_XFldWPS_parent_M_WPSystem_wpclsQuerySettingsPageSize(somSelf,
                                                                   pSizl);
    if (brc) {
        pSizl->cy = 170;        // this is the height of the "WPS Classes" page,
                                // which seems to be the largest in the "Workplace
                                // Shell" object
        if (doshIsWarp4())
            // on Warp 4, reduce again, because we're moving
            // the notebook buttons to the bottom
            pSizl->cy -= WARP4_NOTEBOOK_OFFSET;
    }
    return (brc);
}

/*
 *@@ wpclsQueryTitle:
 *      this WPObject class method tells the WPS the clear
 *      name of a class, which is shown in the third column
 *      of a Details view and also used as the default title
 *      for new objects of a class.
 */

SOM_Scope PSZ  SOMLINK xfwpsM_wpclsQueryTitle(M_XFldWPS *somSelf)
{
    // M_XFldWPSData *somThis = M_XFldWPSGetData(somSelf);
    M_XFldWPSMethodDebug("M_XFldWPS","xfwpsM_wpclsQueryTitle");

    return ("Workplace Shell");
}

/*
 *@@ wpclsQueryIconData:
 *      this WPObject class method builds the default
 *      icon for objects of a class (i.e. the icon which
 *      is shown if no instance icon is assigned). This
 *      apparently gets called from some of the other
 *      icon instance methods if no instance icon was
 *      found for an object. The exact mechanism of how
 *      this works is not documented.
 *
 *      We give the "Workplace Shell" object a new icon.
 */

SOM_Scope ULONG  SOMLINK xfwpsM_wpclsQueryIconData(M_XFldWPS *somSelf,
                                                   PICONINFO pIconInfo)
{
    // M_XFldWPSData *somThis = M_XFldWPSGetData(somSelf);
    M_XFldWPSMethodDebug("M_XFldWPS","xfwpsM_wpclsQueryIconData");

    if (pIconInfo)
    {
        pIconInfo->fFormat = ICON_RESOURCE;
        pIconInfo->resid   = ID_ICONWPS;
        pIconInfo->hmod    = cmnQueryMainResModuleHandle();
    }

    return (sizeof(ICONINFO));
}


