
/*
 *@@sourcefile xwpmouse.c:
 *      This file contains SOM code for the following XWorkplace classes:
 *
 *      --  XWPMouse (WPMouse replacement)
 *
 *      This class replaces the WPMouse class, which implements the
 *      "Mouse" settings object, to introduce new settings pages
 *      for sliding focus and such. This is all new with V0.9.0.
 *
 *      Installation of this class is optional, but you won't
 *      be able to influence certain XWorkplace hook settings without it.
 *
 *      Starting with V0.9.0, the files in classes\ contain only
 *      the SOM interface, i.e. the methods themselves.
 *      The implementation for this class is in in filesys\hookintf.c.
 *
 *@@added V0.9.0 [umoeller]
 *
 *@@somclass XWPMouse xms_
 *@@somclass M_XWPMouse xmsM_
 */

/*
 *      Copyright (C) 1999 Ulrich M”ller.
 *      This file is part of the XWorkplace source package.
 *      XWorkplace is free software; you can redistribute it and/or modify
 *      it under the terms of the GNU General Public License as published
 *      by the Free Software Foundation, in version 2 as it comes in the
 *      "COPYING" file of the XWorkplace main distribution.
 *      This program is distributed in the hope that it will be useful,
 *      but WITHOUT ANY WARRANTY; without even the implied warranty of
 *      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *      GNU General Public License for more details.
 */

/*
 *  This file was generated by the SOM Compiler and Emitter Framework.
 *  Generated using:
 *      SOM Emitter emitctm: 2.41
 */

#ifndef SOM_Module_xwpmouse_Source
#define SOM_Module_xwpmouse_Source
#endif
#define XWPMouse_Class_Source
#define M_XWPMouse_Class_Source

/*
 *  Suggested #include order:
 *  1)  os2.h
 *  2)  C library headers
 *  3)  setup.h (code generation and debugging options)
 *  4)  headers in helpers\
 *  5)  at least one SOM implementation header (*.ih)
 *  6)  dlgids.h, headers in shared\ (as needed)
 *  7)  headers in implementation dirs (e.g. filesys\, as needed)
 *  8)  #pragma hdrstop and then more SOM headers which crash with precompiled headers
 */

#include <os2.h>

// C library headers
#include <stdio.h>

// generic headers
#include "setup.h"                      // code generation and debugging options

// headers in /helpers

// SOM headers which don't crash with prec. header files
#include "xwpmouse.ih"

// XWorkplace implementation headers
#include "dlgids.h"                     // all the IDs that are shared with NLS
#include "shared\common.h"              // the majestic XWorkplace include file
#include "shared\notebook.h"            // generic XWorkplace notebook handling

#include "config\hookintf.h"            // daemon/hook interface

// other SOM headers
#pragma hdrstop

/*
 *@@ xwpAddMouseMovementPage:
 *      this actually adds the "Movement" page into the
 *      "Mouse" notebook to configure the XWorkplace hook.
 *      Gets called by XWPMouse::wpAddMouseCometPage.
 */

SOM_Scope ULONG  SOMLINK xms_xwpAddMouseMovementPage(XWPMouse *somSelf,
                                                     HWND hwndDlg)
{
    PCREATENOTEBOOKPAGE pcnbp;
    HMODULE             savehmod = cmnQueryNLSModuleHandle(FALSE);
    PCGLOBALSETTINGS    pGlobalSettings = cmnQueryGlobalSettings();
    PNLSSTRINGS         pNLSStrings = cmnQueryNLSStrings();
    ULONG               ulrc = 0;

    /* XWPMouseData *somThis = XWPMouseGetData(somSelf); */
    XWPMouseMethodDebug("XWPMouse","xms_xwpAddMouseMovementPage");

    // insert "MouseHook" page if the hook has been enabled
    if (hifXWPHookReady())
    {
        pcnbp = malloc(sizeof(CREATENOTEBOOKPAGE));
        memset(pcnbp, 0, sizeof(CREATENOTEBOOKPAGE));
        pcnbp->somSelf = somSelf;
        pcnbp->hwndNotebook = hwndDlg;
        pcnbp->hmod = savehmod;
        pcnbp->ulDlgID = ID_XSD_MOUSEHOOK;
        pcnbp->usPageStyleFlags = BKA_MAJOR;
        pcnbp->pszName = pNLSStrings->pszMouseHookPage;
        pcnbp->ulDefaultHelpPanel  = ID_XSH_MOUSEHOOK;
        pcnbp->ulPageID = SP_MOUSEHOOK;
        pcnbp->pfncbInitPage    = hifMouseMovementInitPage;
        pcnbp->pfncbItemChanged = hifMouseMovementItemChanged;
        ulrc = ntbInsertPage(pcnbp);
    }

    return (ulrc);
}

/*
 *@@ xms_xwpAddMouseMappings2Page:
 *      this adds the second "Mappings" page to the
 *      "Mouse" settings notebook after the WPS's
 *      standard "Mappings" page.
 *      Gets called by XWPMouse::wpAddMouseMappingsPage.
 *
 *@@added V0.9.1 [umoeller]
 */

SOM_Scope ULONG  SOMLINK xms_xwpAddMouseMappings2Page(XWPMouse *somSelf,
                                                      HWND hwndDlg)
{
    PCREATENOTEBOOKPAGE pcnbp;
    HMODULE             savehmod = cmnQueryNLSModuleHandle(FALSE);
    PCGLOBALSETTINGS    pGlobalSettings = cmnQueryGlobalSettings();
    PNLSSTRINGS         pNLSStrings = cmnQueryNLSStrings();
    ULONG               ulrc = 0;

    /* XWPMouseData *somThis = XWPMouseGetData(somSelf); */
    XWPMouseMethodDebug("XWPMouse","xms_xwpAddMouseMappings2Page");

    // insert "MouseHook" page if the hook has been enabled
    if (hifXWPHookReady())
    {
        pcnbp = malloc(sizeof(CREATENOTEBOOKPAGE));
        memset(pcnbp, 0, sizeof(CREATENOTEBOOKPAGE));
        pcnbp->somSelf = somSelf;
        pcnbp->hwndNotebook = hwndDlg;
        pcnbp->hmod = savehmod;
        pcnbp->ulDlgID = ID_XSD_MOUSEMAPPINGS2;
        pcnbp->usPageStyleFlags = BKA_MINOR;
        pcnbp->pszName = pNLSStrings->pszMappingsPage;
        pcnbp->ulDefaultHelpPanel  = ID_XSH_MOUSEMAPPINGS2;
        pcnbp->ulPageID = SP_MOUSEMAPPINGS2;
        pcnbp->pfncbInitPage    = hifMouseMappings2InitPage;
        pcnbp->pfncbItemChanged = hifMouseMappings2ItemChanged;
        ulrc = ntbInsertPage(pcnbp);
    }

    return (ulrc);
}

/*
 *@@ xwpAddAnimatedMousePointerPage:
 *      this inserts the animated "mouse pointer" replacement
 *      page into the "Mouse" notebook.
 */

SOM_Scope ULONG  SOMLINK xms_xwpAddAnimatedMousePointerPage(XWPMouse *somSelf,
                                                            HWND hwndDlg)
{
    /* XWPMouseData *somThis = XWPMouseGetData(somSelf); */
    XWPMouseMethodDebug("XWPMouse","xms_xwpAddAnimatedMousePointerPage");

    // ### this is the place where to insert the animated mouse
    // pointers page

    return (0);
}

/*
 *@@ wpInitData:
 *      init instance data.
 */

SOM_Scope void  SOMLINK xms_wpInitData(XWPMouse *somSelf)
{
    /* XWPMouseData *somThis = XWPMouseGetData(somSelf); */
    XWPMouseMethodDebug("XWPMouse","xms_wpInitData");

    XWPMouse_parent_WPMouse_wpInitData(somSelf);
}

/*
 *@@ wpUnInitData:
 *      clean up instance data.
 */

SOM_Scope void  SOMLINK xms_wpUnInitData(XWPMouse *somSelf)
{
    /* XWPMouseData *somThis = XWPMouseGetData(somSelf); */
    XWPMouseMethodDebug("XWPMouse","xms_wpUnInitData");

    XWPMouse_parent_WPMouse_wpUnInitData(somSelf);
}

/*
 *@@ wpSetup:
 *      this instance method is called to allow the newly
 *      created object to initialize itself based on an input
 *      setup string.
 */

SOM_Scope BOOL  SOMLINK xms_wpSetup(XWPMouse *somSelf, PSZ pszSetupString)
{
    /* XWPMouseData *somThis = XWPMouseGetData(somSelf); */
    XWPMouseMethodDebug("XWPMouse","xms_wpSetup");

    return (XWPMouse_parent_WPMouse_wpSetup(somSelf, pszSetupString));
}

/*
 *@@ wpSaveState:
 *      this WPObject instance method saves an object's state
 *      persistently.
 */

SOM_Scope BOOL  SOMLINK xms_wpSaveState(XWPMouse *somSelf)
{
    /* XWPMouseData *somThis = XWPMouseGetData(somSelf); */
    XWPMouseMethodDebug("XWPMouse","xms_wpSaveState");

    return (XWPMouse_parent_WPMouse_wpSaveState(somSelf));
}

/*
 *@@ wpRestoreState:
 *      this WPObject instance method gets called during object
 *      initialization to restore the data which was stored with
 *      wpSaveState.
 */

SOM_Scope BOOL  SOMLINK xms_wpRestoreState(XWPMouse *somSelf,
                                           ULONG ulReserved)
{
    /* XWPMouseData *somThis = XWPMouseGetData(somSelf); */
    XWPMouseMethodDebug("XWPMouse","xms_wpRestoreState");

    return (XWPMouse_parent_WPMouse_wpRestoreState(somSelf, ulReserved));
}

/*
 *@@ wpAddMouseCometPage:
 *      this WPMouse instance method inserts the "Comet"
 *      page into the mouse object's settings notebook.
 *      We override this to get an opportunity to insert our
 *      own pages behind that page by calling
 *      XWPMouse::xwpAddMouseMovementPage to configure the hook.
 */

SOM_Scope ULONG  SOMLINK xms_wpAddMouseCometPage(XWPMouse *somSelf,
                                                 HWND hwndNotebook)
{
    /* XWPMouseData *somThis = XWPMouseGetData(somSelf); */
    XWPMouseMethodDebug("XWPMouse","xms_wpAddMouseCometPage");

    _xwpAddMouseMovementPage(somSelf, hwndNotebook);

    return (XWPMouse_parent_WPMouse_wpAddMouseCometPage(somSelf,
                                                        hwndNotebook));
}


/*
 *@@ wpAddMousePtrPage:
 *      this WPMouse instance method inserts the "Pointers"
 *      page in the "Mouse" object's settings notebook.
 *      We override this to insert the animated mouse pointers
 *      page instead.
 *
 *@@added V0.9.1 [umoeller]
 */

SOM_Scope ULONG  SOMLINK xms_wpAddMousePtrPage(XWPMouse *somSelf,
                                               HWND hwndNotebook)
{
    /* XWPMouseData *somThis = XWPMouseGetData(somSelf); */
    XWPMouseMethodDebug("XWPMouse","xms_wpAddMousePtrPage");

    return (XWPMouse_parent_WPMouse_wpAddMousePtrPage(somSelf,
                                                      hwndNotebook));
}

/*
 *@@ xms_wpAddMouseMappingsPage:
 *      this WPMouse instance method inserts the "Mappings"
 *      page in the "Mouse" object's settings notebook.
 *      We override this to insert a second "Mappings" page
 *      for configuring more XWorkplace hook features.
 *
 *@@added V0.9.1 [umoeller]
 */

SOM_Scope ULONG  SOMLINK xms_wpAddMouseMappingsPage(XWPMouse *somSelf,
                                                    HWND hwndNotebook)
{
    /* XWPMouseData *somThis = XWPMouseGetData(somSelf); */
    XWPMouseMethodDebug("XWPMouse","xms_wpAddMouseMappingsPage");

    _xwpAddMouseMappings2Page(somSelf, hwndNotebook);

    return (XWPMouse_parent_WPMouse_wpAddMouseMappingsPage(somSelf,
                                                           hwndNotebook));
}


/*
 *@@ wpclsInitData:
 *      initialize XWPMouse class data.
 */

SOM_Scope void  SOMLINK xmsM_wpclsInitData(M_XWPMouse *somSelf)
{
    /* M_XWPMouseData *somThis = M_XWPMouseGetData(somSelf); */
    M_XWPMouseMethodDebug("M_XWPMouse","xmsM_wpclsInitData");

    M_XWPMouse_parent_M_WPMouse_wpclsInitData(somSelf);
}

/*
 *@@ wpclsQuerySettingsPageSize:
 *      this WPObject class method should return the
 *      size of the largest settings page in dialog
 *      units; if a settings notebook is initially
 *      opened, i.e. no window pos has been stored
 *      yet, the WPS will use this size, to avoid
 *      truncated settings pages.
 */

SOM_Scope BOOL  SOMLINK xmsM_wpclsQuerySettingsPageSize(M_XWPMouse *somSelf,
                                                        PSIZEL pSizl)
{
    /* M_XWPMouseData *somThis = M_XWPMouseGetData(somSelf); */
    M_XWPMouseMethodDebug("M_XWPMouse","xmsM_wpclsQuerySettingsPageSize");

    return (M_XWPMouse_parent_M_WPMouse_wpclsQuerySettingsPageSize(somSelf,
                                                                   pSizl));
}

