
/*
 * anwani.idl  - XWPWinAni
 *
 */

#ifndef anwani_idl
#define anwani_idl

#include "wpdataf.idl"
#include <somcls.idl>

interface M_XWPWinAni;

interface XWPWinAni : WPDataFile
{
   // neue Methoden
   VOID  xwpRefreshFileIcon();
   ULONG xwpGetAnimationTimeframeValue();
   BOOL  xwpSetAnimationTimeframeValue( in ULONG ulNewValue);
   ULONG xwpInsertAnimationPage1( in HWND hwndDlg );
   ULONG xwpInsertAnimationPage2( in HWND hwndDlg );
   ULONG xwpInsertAnimationPage3( in HWND hwndDlg );

   #ifdef __SOMIDL__
   implementation
   {
      releaseorder:
         xwpRefreshFileIcon,
         xwpGetAnimationTimeframeValue,
         xwpSetAnimationTimeframeValue,
         xwpInsertAnimationPage1,
         xwpInsertAnimationPage2,
         xwpInsertAnimationPage3;

      /*
       * Class Modifiers
       */
      functionprefix = wani_;
      externalprefix = wani_;
      local;
      majorversion   = 1;
      minorversion   = 2;
      filestem       = anwani;
      metaclass      = M_XWPWinAni;
      callstyle      = oidl;
      dllname        = "xfldr.dll";

      /*
       * Internal Instance Variables
       */
      PICONINFO       piconinfo;
      HPOINTER        hptr;
      ULONG           ulDataLen;
      PVOID           pfs3;
      ULONG           ulLastStyle;

      HPOINTER       *phpointerTable;
      ULONG          *pulTimeoutTable;
      ULONG           ulAnimationCount;

      /*
       * Method Modifiers
       */

      wpAddFile1Page:                  override;
      wpAddObjectGeneralPage:          override;
      wpObjectReady:                   override;
      wpQueryIcon:                     override;
      wpQueryIconData:                 override;
      wpSetIcon:                       override;
      wpSetIconData:                   override;

      wpModifyPopupMenu:               override;
      wpFilterPopupMenu:               override;
      wpMenuItemSelected:              override;
      wpMenuItemHelpSelected:          override;

      wpInitData:                      override;
      wpUnInitData:                    override;

   };
   #endif /* __SOMIDL__ */
};

interface M_XWPWinAni : M_WPDataFile
{
   #ifdef __SOMIDL__
   implementation
   {
      /*
       * Class Modifiers
       */
      functionprefix = waniM_;
      externalprefix = waniM_;
      local;
      majorversion   = 1;
      minorversion   = 2;
      filestem       = anwani;
      callstyle      = oidl;
      dllname        = "xfldr.dll";

      /*
       * Method Modifiers
       */

      wpclsQueryStyle:                 override;
      wpclsQueryInstanceFilter:        override;
      wpclsQueryInstanceType:          override;
      wpclsQueryTitle:                 override;
      wpclsInitData:                   override;
      wpclsUnInitData:                 override;
   };
   #endif /* __SOMIDL__ */
};
#endif  /* anwani_idl */

