
/*
 * xcenter.idl:
 *      SOM interface description file for the following
 *      XWorkplace classes (in this order):
 *          XCenter
 *      and the respective metaclasses.
 *
 *      See src\classes\xcenter.c for details.
 *
 *      Copyright (C) 2000 Ulrich M”ller.
 *      This file is part of the XWorkplace source package.
 *      XWorkplace is free software; you can redistribute it and/or modify
 *      it under the terms of the GNU General Public License as published
 *      by the Free Software Foundation, in version 2 as it comes in the
 *      "COPYING" file of the XWorkplace main distribution.
 *      This program is distributed in the hope that it will be useful,
 *      but WITHOUT ANY WARRANTY; without even the implied warranty of
 *      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *      GNU General Public License for more details.
 */

#include <wpabs.idl>         // this is SOM for WPAbstract

/*
   CLASS: XCenter

   CLASS HIERARCHY:

       SOMObject
         ÀÄÄ WPObject
               ÀÄÄ WPAbstract
                     ÀÄÄ XCenter
*/

interface M_XCenter;            // forward reference to metaclass

interface XCenter : WPAbstract
{
    /*
     * New instance methods for XCenter:
     *
     */

    ULONG xwpAddXCenterPages(in HWND hwndNotebook);

    PVOID xwpQueryWidgets(in PULONG pulCount);

    VOID xwpFreeWidgetsBuf(in PVOID pBuf,
                           in ULONG ulCount);

    BOOL xwpInsertWidget(in ULONG ulBeforeIndex,
                         in PSZ pszWidgetClass,
                         in PSZ pszSetupString);

    BOOL xwpRemoveWidget(in ULONG ulIndex);

    BOOL xwpMoveWidget(in ULONG ulIndex2Move,
                       in ULONG ulBeforeIndex);

    BOOL xwpSetPriority(in ULONG ulClass,
                        in LONG lDelta);

    ULONG xwpQuerySetup2(in PSZ pszSetupString,
                         in ULONG cbSetupString);

#ifdef __SOMIDL__
  implementation {

    releaseorder: xwpAddXCenterPages,
                  xwpQueryWidgets,
                  xwpFreeWidgetsBuf,
                  xwpInsertWidget,
                  xwpRemoveWidget,
                  xwpMoveWidget,
                  xwpSetPriority,
                  xwpQuerySetup2;

    /*
     * Class Modifiers:
     *
     */

    externalprefix = xctr_;
    externalstem = xctr;
    majorversion = 1;
    minorversion = 1;
    filestem = xcenter;           //# specifies the filestem for sc-generated files
    metaclass = M_XCenter;
    dllname = "xfldr.dll";
    callstyle = oidl;           //# forget CORBA stuff (*ev and such)

    /*
     * Internal instance variables for XCenter:
     *
     */

    BOOL fReduceDesktopWorkarea;    // if TRUE, this XCenter will reduce the desktop
                                    // workarea if open

    ULONG ulWindowStyle;            // XCenter frame's window style;
                                    // defaults to 0, but can be WS_TOPMOST | WS_ANIMATE

    ULONG ulAutoHide;               // auto-hide delay in milliseconds; if 0,
                                    // auto-hide is off

    ULONG ulPosition;               // 0 = bottom (XCENTER_BOTTOM)
                                    // 1 = top (XCENTER_TOP)

    ULONG flDisplayStyle;           // XCS_* style flags. See XCENTERGLOBALS.

    ULONG ul3DBorderWidth;          // 3D border width of entire XCenter (0-10)
    ULONG ulBorderSpacing;          // spacing between 3D border and widgets (0-10)
    ULONG ulWidgetSpacing;          // spacing between widgets

    ULONG ulPriorityClass;          // XCenter priority class
    LONG lPriorityDelta;            // XCenter priority delta

    BOOL fHelpDisplayed;            // TRUE after the first open of the XCenter,
                                    // when introductory help has been displayed.

    PVOID pvOpenView;               // if != NULLHANDLE, XCenter is currently open,
                                    // and this has a PXCENTERWINDATA pointer
                                    // which contains all the view data...

    ULONG tid;                      // thread ID of running XCenter thread or null

    BOOL fShowingOpenViewMenu;      // TRUE if context menu on XCenter client

    PSZ pszPackedWidgetSettings;    // packed widget settings restored in wpRestoreState
                                    // (allocated with malloc())
    ULONG cbPackedWidgetSettings;   // size of that buffer

    PVOID pllWidgetSettings;        // linked list of XCENTERWIDGETSETTING entries
                                    // (this is a PLINKLIST really)

    /*
     * WPAbstract methods overridden by XCenter:
     *
     */

    wpInitData: override;
    wpUnInitData: override;
    wpObjectReady: override;

    wpSetup: override;

    wpSaveState: override;
    wpRestoreState: override;

    wpModifyPopupMenu: override;

    wpQueryDefaultHelp: override;
    wpQueryDefaultView: override;

    wpOpen: override;
    wpSwitchTo: override;

    wpAddObjectWindowPage: override;

    wpAddSettingsPages: override;

  }; // implementation
#endif /* __SOMIDL__ */
};

//#
//#
//# Now define Metaclass.
//# ---------------------
//#

interface M_XCenter : M_WPAbstract
{

#ifdef __SOMIDL__
  implementation {

    /*
     * Class Modifiers:
     *
     */

    externalprefix = xctrM_;
    externalstem = xctrM;
    functionprefix = xctrM_;
    majorversion = 1;
    minorversion = 1;
    filestem = xcenter;           //# specifies the filestem for sc-generated files
    dllname = "xfldr.dll";
    callstyle = oidl;

    /*
     * Internal class variables:
     *
     */

    /*
     * M_WPAbstract methods overridden by M_XCenter:
     *
     */

    wpclsInitData: override;
    wpclsQueryStyle: override;
    wpclsQueryTitle: override;

    wpclsCreateDefaultTemplates: override;

    wpclsQueryIconData: override;
  };
#endif /* __SOMIDL__ */
};


