
/*
 * xfdataf.idl:
 *      SOM interface description file for the following
 *      XWorkplace classes (in this order):
 *          XFldDataFile
 *      and the respective metaclasses.
 *
 *      See src\classes\xfdataf.c for details.
 *
 *      Copyright (C) 1997-2002 Ulrich M”ller.
 *      This file is part of the XWorkplace source package.
 *      XWorkplace is free software; you can redistribute it and/or modify
 *      it under the terms of the GNU General Public License as published
 *      by the Free Software Foundation, in version 2 as it comes in the
 *      "COPYING" file of the XWorkplace main distribution.
 *      This program is distributed in the hope that it will be useful,
 *      but WITHOUT ANY WARRANTY; without even the implied warranty of
 *      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *      GNU General Public License for more details.
 */

#include <wpdataf.idl>          // this is SOM for WPDataFile

/*
   CLASS: XFldDataFile

   CLASS HIERARCHY:

       SOMObject
         ÀÄÄ WPObject = XFldObject
               ÀÄÄ WPFileSystem
                     ÀÄÄ WPDataFile
                           ÀÄÄ  XFldDataFile
*/

interface M_XFldDataFile;            // forward reference to metaclass

interface XFldDataFile : WPDataFile
{

    /*
     * New instance methods for XFldDataFile:
     *
     */

    BOOL xwpDestroyStorage();

#ifdef __SOMIDL__
  implementation {

    releaseorder: xwpDestroyStorage;

    /*
     * Class Modifiers:
     *
     */

    externalprefix = xdf_;
    externalstem = xdf;
    majorversion = 1;
    minorversion = 1;
    filestem = xfdataf;           //# specifies the filestem for sc-generated files
    metaclass = M_XFldDataFile;
    dllname = "xfldr.dll";
    callstyle = oidl;           //# forget CORBA stuff (*ev and such)

    /*
     * Internal instance variables for XFldDataFile:
     *
     */

    BOOL        fHasIconEA;            // set to TRUE in wpRestoreState if so

    /*
     * The following is forced into the .H file:
     *
     */

    /*
     * WPDataFile methods overridden by XFldDataFile:
     *
     */

    wpInitData: override;
    wpRestoreState: override;

    wpDisplayMenu: override;
    wpFilterPopupMenu: override;
    wpModifyPopupMenu: override;

    wpMenuItemHelpSelected: override;

    wpOpen: override;

    wpAddFile1Page: override;
    wpAddFile2Page: override;
    wpAddFile3Page: override;

    wpAddFileTypePage: override;

    wpQueryDefaultHelp: override;
    wpQueryAssociatedProgram: override;
    wpQueryAssociatedFileIcon: override;
    wpSetAssociatedFileIcon: override;

    wpQueryIcon: override;
    wpQueryIconData: override;
    wpSetIconData: override;

#ifdef __PRIVATE__

#endif

  }; // implementation
#endif /* __SOMIDL__ */
};

//#
//#
//# Now define Metaclass.
//# ---------------------
//#

interface M_XFldDataFile : M_WPDataFile
{

#ifdef __SOMIDL__
  implementation {

    /*
     * Class Modifiers:
     *
     */

    externalprefix = xdfM_;
    externalstem = xdfM;
    functionprefix = xdfM_;
    majorversion = 1;
    minorversion = 1;
    filestem = xfdataf;           //# specifies the filestem for sc-generated files
    dllname = "xfldr.dll";
    callstyle = oidl;

    /*
     * Internal class variables for M_XFldDataFile:
     *
     */

    /*
     * M_WPDataFile methods overridden by M_XFldDataFile:
     *
     */

    wpclsInitData: override;
    wpclsCreateDefaultTemplates: override;

    wpclsQueryTitle: override;

    wpclsQueryIconData: override;

  };
#endif /* __SOMIDL__ */
};


