
/*
 * xfobj.idl:
 *      SOM interface description file for the following
 *      XWorkplace classes (in this order):
 *          XFldObject
 *      and the respective metaclasses.
 *
 *      See src\classes\xfobj.c for details.
 *
 *      Copyright (C) 1997-2000 Ulrich M”ller.
 *      This file is part of the XWorkplace source package.
 *      XWorkplace is free software; you can redistribute it and/or modify
 *      it under the terms of the GNU General Public License as published
 *      by the Free Software Foundation, in version 2 as it comes in the
 *      "COPYING" file of the XWorkplace main distribution.
 *      This program is distributed in the hope that it will be useful,
 *      but WITHOUT ANY WARRANTY; without even the implied warranty of
 *      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *      GNU General Public License for more details.
 */

#include <wpobject.idl>         // this is SOM for WPObject

/*
   CLASS: XFldObject

   CLASS HIERARCHY:

       SOMObject
         ÀÄÄ WPObject
               ÀÄÄ XFldObject
*/

interface M_XFldObject;            // Forward Reference to XFldObject metaclass

interface XFldObject : WPObject
{

    /*
     *@@ WPOBJECTDATA:
     *      internal data structure for WPObject
     *      settings. We store a pointer to the
     *      instance's structure in _pWPObjectData,
     *      which is examined in _wpRestoreData.
     *
     *@@added V0.9.1 (2000-01-22) [umoeller]
     */

    struct WPOBJECTDATASTRUCT
    {
        LONG  lDefaultView;
        ULONG ulHelpPanel;      // 0 means default, apparently
        ULONG ulUnknown3;
        ULONG ulObjectStyle;
        ULONG ulMinWin;         // MINWIN_DEFAULT=0, MINWIN_HIDDEN=1, MINWIN_VIEWER=2, MINWIN_DESKTOP=3
        ULONG ulConcurrent;     // CCVIEW_DEFAULT=0, CCVIEW_ON=1, CCVIEW_OFF=2
        ULONG ulViewButton;     // HIDEBUTTON=1, MINBUTTON=2, DEFAULTBUTTON=3
        ULONG ulMenuFlag;       // 2?
    };
    typedef WPOBJECTDATASTRUCT *PWPOBJECTDATASTRUCT;

    /*
     * New instance methods for XFldObject:
     *
     */

    ULONG xwpAddObjectInternalsPage(in HWND hwndNotebook);

    BOOL xwpQueryDeletion(in CDATE* pcdateDeleted, in CTIME* pctimeDeleted);
    BOOL xwpSetDeletion(in BOOL fSet);

    BOOL xwpSetTrashObject(in WPObject pTrashObject);

    ULONG xwpQueryListNotify();
    BOOL xwpSetListNotify(in ULONG flNotifyFlags);
    BOOL xwpModifyListNotify(in ULONG flNotifyFlags,
                             in ULONG flNotifyMask);

    BOOL xwpAddDestroyNotify(in HWND hwnd);
    BOOL xwpRemoveDestroyNotify(in HWND hwnd);

    BOOL xwpQueryObjectHotkey(in PUSHORT pusFlags,
                              in PUCHAR  pucScanCode,
                              in PUSHORT pusKeyCode);
    BOOL xwpSetObjectHotkey(in USHORT usFlags,
                            in UCHAR ucScanCode,
                            in USHORT usKeyCode);

    ULONG xwpQuerySetup(in PSZ pszSetupString,
                        in ULONG cbSetupString);

    ULONG xwpQuerySetup2(in PSZ pszSetupString,
                         in ULONG cbSetupString);

#ifdef __SOMIDL__
  implementation {

    releaseorder: xwpAddObjectInternalsPage,
                  xwpQueryDeletion,
                  xwpSetDeletion,
                  xwpSetTrashObject,
                  xwpQueryObjectHotkey,
                  xwpSetObjectHotkey,
                  xwpQuerySetup,
                  xwpQuerySetup2,
                  xwpQueryListNotify,
                  xwpSetListNotify,
                  xwpModifyListNotify,
                  xwpAddDestroyNotify,
                  xwpRemoveDestroyNotify;

    //# Class Modifiers
    externalprefix = xfobj_;
    externalstem = xfobj;
    majorversion = 1;
    minorversion = 1;
    filestem = xfobj;           //# specifies the filestem for sc-generated files
    metaclass = M_XFldObject;
    dllname = "xfldr.dll";
    callstyle = oidl;           //# forget CORBA stuff (*ev and such)

    /*
     * Internal instance variables for XFldObject:
     *
     */

    // the following have been added with V0.9.0
    BOOL        fDeleted;       // if TRUE, the following two fields are valid
    CDATE       cdateDeleted;   // data for xwpQueryDeletion, if fDeleted == TRUE
    CTIME       ctimeDeleted;   // data for xwpQueryDeletion, if fDeleted == TRUE

    // the following have been added with V0.9.2
    PWPOBJECTDATASTRUCT pWPObjectData;
    ULONG       cbWPObjectData;

    WPObject    pTrashObject;   // if the object has been deleted, this is the
                                // corresponding trash object; this is set when
                                // the trash object is created (upon deletion
                                // or upon first trash can populate)

    ULONG       ulListNotify;   // OBJLIST_* flags set with xwpSetListNotify

    PVOID       pvllWidgetNotifies; // really a PLINKLIST for xwpSetWidgetNotify

    /*
     * The following is forced into the .H file:
     *
     */

    /*
     * WPObject methods overridden by XFldObject:
     *
     */

    wpInitData: override;
    wpCopyObject: override;
    wpObjectReady: override;

    wpUnInitData: override;

    wpSaveState: override;
    wpRestoreState: override;
    wpRestoreData: override;

    wpDisplayMenu: override;
    wpFilterPopupMenu: override;
    wpModifyPopupMenu: override;
    wpMenuItemSelected: override;

    //# wpAddSettingsPages: override;
    wpAddObjectGeneralPage: override;

    wpConfirmObjectTitle: override;
    wpDelete: override;

#ifdef __PRIVATE__

#endif

  }; // implementation
#endif /* __SOMIDL__ */
};

//#
//#
//# Now define Metaclass.
//# ---------------------
//#

interface M_XFldObject : M_WPObject
{

    /*
     * New class methods  for M_XFldObject:
     *
     */

    BOOL xwpclsRemoveObjectHotkey(in HOBJECT hobj);

#ifdef __SOMIDL__
  implementation {

    releaseorder:
                xwpclsRemoveObjectHotkey;

    //# Class Modifiers
    externalprefix = xfobjM_;
    externalstem = xfobjM;
    functionprefix = xfobjM_;
    majorversion = 1;
    minorversion = 1;
    filestem = xfobj;           //# specifies the filestem for sc-generated files
    dllname = "xfldr.dll";
    callstyle = oidl;

    /*
     * Internal class variables for M_XFldObject:
     *
     */

    /*
     * M_WPObject methods overridden by M_XFldObject:
     *
     */

    wpclsInitData: override;
    wpclsNew: override;
    wpclsMakeAwake: override;

    wpclsQuerySettingsPageSize: override;
  };
#endif /* __SOMIDL__ */
};


