
/*
 * xtrash.idl:
 *      SOM interface description file for the following
 *      XWorkplace classes (in this order):
 *
 *      --  XWPTrashCan: a subclass of WPFolder, which implements
 *                       the actual trash can folder.
 *
 *      See src\classes\xtrash.c for details.
 *
 *      Copyright (C) 1999-2000 Ulrich M”ller.
 *      This file is part of the XWorkplace source package.
 *      XWorkplace is free software; you can redistribute it and/or modify
 *      it under the terms of the GNU General Public License as published
 *      by the Free Software Foundation, in version 2 as it comes in the
 *      "COPYING" file of the XWorkplace main distribution.
 *      This program is distributed in the hope that it will be useful,
 *      but WITHOUT ANY WARRANTY; without even the implied warranty of
 *      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *      GNU General Public License for more details.
 */

#include <wpfolder.idl>         // this is SOM for WPFolder

/*
   CLASS: XWPTrashCan

   CLASS HIERARCHY:

       SOMObject
         ÀÄÄ WPObject [ = XFldObject ]
               ÀÄÄ WPFileSystem
                     ÀÄÄ WPFolder [ = XFolder ]
                           ÀÄÄ XWPTrashCan
*/

interface M_XWPTrashCan;            // forward reference to metaclass

interface XWPTrashCan : WPFolder
{

    /*
     * New instance methods for XWPTrashCan:
     *
     */

    BOOL xwpDeleteIntoTrashCan(in WPObject pObject);

    ULONG xwpAddTrashCanSettingsPage(in HWND hwndDlg);
    ULONG xwpAddTrashCanDrivesPage(in HWND hwndDlg);
    ULONG xwpAddTrashCanGeneralPage(in HWND hwndDlg);

    BOOL xwpTrashCanBusy(in SHORT sBusy);
    VOID xwpAddObjectSize(in ULONG ulNewSize);
    ULONG xwpQueryTrashObjectsCount();

    BOOL xwpSetCorrectTrashIcon(in BOOL fForce);

    BOOL xwpEmptyTrashCan(in BOOL fConfirm);

    BOOL xwpUpdateStatusBar(in HWND hwndStatusBar, in HWND hwndCnr);

#ifdef __SOMIDL__
  implementation {

    releaseorder:
            xwpDeleteIntoTrashCan,
            xwpAddTrashCanSettingsPage,
            xwpAddTrashCanDrivesPage,
            xwpAddTrashCanGeneralPage,
            xwpTrashCanBusy,
            xwpAddObjectSize,
            xwpQueryTrashObjectsCount,
            xwpSetCorrectTrashIcon,
            xwpEmptyTrashCan,
            xwpUpdateStatusBar;

    /*
     * Class Modifiers:
     *
     */

    externalprefix = xtrc_;
    externalstem = xtrc;
    majorversion = 1;
    minorversion = 1;
    filestem = xtrash;           //# specifies the filestem for sc-generated files
    metaclass = M_XWPTrashCan;
    dllname = "xfldr.dll";
    callstyle = oidl;           //# forget CORBA stuff (*ev and such)

    /*
     * Internal instance variables for XWPTrashCan:
     *
     */

    BOOL    fAlreadyPopulated;      // TRUE after the first call to wpPopulate
    BOOL    fFilledIconSet;         // TRUE if "filled" icon has been set already

    ULONG   ulTrashObjectCount;     // no. of trash objects in trash can;
                                    // initialized to 0, updated by wpPopulate

    double  dSizeOfAllObjects;      // size of all objects in trash can

    CHAR    cDrivePopulating;       // if this is != 0, a drive is currently
                                    // being populated; set by wpPopulate and
                                    // used for the status bar

    ULONG   ulBusyCount;            // raised or lowered with every xwpTrashCanBusy call

    /*
     * WPFolder methods overridden by XWPTrashCan:
     *
     */

    wpInitData: override;
    wpObjectReady: override;
    wpUnInitData: override;
    wpSetup: override;

    wpSaveState: override;
    wpRestoreState: override;

    wpFilterPopupMenu: override;
    wpModifyPopupMenu: override;
    wpMenuItemSelected: override;
    wpMenuItemHelpSelected: override;

    wpQueryDefaultHelp: override;

    wpOpen: override;
    wpPopulate: override;
    wpRefresh: override;

    wpAddToContent: override;
    wpDeleteFromContent: override;

    wpDragOver: override;
    wpDrop: override;

    wpAddObjectGeneralPage: override;
    wpAddObjectGeneralPage2: override;
    wpAddFolderIncludePage: override;
    wpAddFolderView2Page: override;

    wpAddSettingsPages: override;

#ifdef __PRIVATE__

#endif

  }; // implementation
#endif /* __SOMIDL__ */
};

//#
//#
//# Now define Metaclass.
//# ---------------------
//#

interface M_XWPTrashCan : M_WPFolder
{

    /*
     * New class methods for M_XWPTrashCan:
     *
     */

    XWPTrashCan xwpclsQueryDefaultTrashCan();
    BOOL xwpclsSetDrivesSupport(in PBYTE pabSupportedDrives);
    BOOL xwpclsQueryDrivesSupport(in PBYTE pabSupportedDrives);

#ifdef __SOMIDL__
  implementation {

    releaseorder: xwpclsQueryDefaultTrashCan,
                  xwpclsSetDrivesSupport,
                  xwpclsQueryDrivesSupport;

    /*
     * Class Modifiers:
     *
     */

    externalprefix = xtrcM_;
    externalstem = xtrcM;
    functionprefix = xtrcM_;
    majorversion = 1;
    minorversion = 1;
    filestem = xtrash;           //# specifies the filestem for sc-generated files
    dllname = "xfldr.dll";
    callstyle = oidl;

    /*
     * Internal instance variables for M_XWPTrashCan:
     *
     */

    /*
     * M_WPFolder methods overridden by M_XWPTrashCan:
     *
     */

    wpclsInitData: override;
    wpclsUnInitData: override;
    wpclsQueryTitle: override;
    wpclsQueryStyle: override;

    wpclsQueryIconData: override;
    wpclsQueryIconDataN: override;

  };
#endif /* __SOMIDL__ */
};


