
/*
 * xwpmouse.idl:
 *      SOM interface description file for the following
 *      XWorkplace classes (in this order):
 *          XWPMouse ("Mouse" object; WPMouse replacement)
 *      and the respective metaclasses.
 *
 *      See src\classes\xwpmouse.c for details.
 *
 *      Copyright (C) 1999 Ulrich M”ller.
 *      This file is part of the XWorkplace source package.
 *      XWorkplace is free software; you can redistribute it and/or modify
 *      it under the terms of the GNU General Public License as published
 *      by the Free Software Foundation, in version 2 as it comes in the
 *      "COPYING" file of the XWorkplace main distribution.
 *      This program is distributed in the hope that it will be useful,
 *      but WITHOUT ANY WARRANTY; without even the implied warranty of
 *      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *      GNU General Public License for more details.
 */

#include <wpmouse.idl>         // this is SOM for WPMouse

/*
   CLASS: XWPMouse

   CLASS HIERARCHY:

       SOMObject
         ÀÄÄ WPObject
               ÀÄÄ WPAbstract
                     ÀÄÄ WPMouse
                           ÀÄÄ  XWPMouse
*/

interface M_XWPMouse;            // forward reference to metaclass

interface XWPMouse : WPMouse
{
    /*
     * New instance methods for XWPMouse:
     *
     */

    ULONG xwpAddMouseMovementPage(in HWND hwndDlg);

    ULONG xwpAddMouseMappings2Page(in HWND hwndDlg);

    ULONG xwpAddAnimatedMousePointerPage(in HWND hwndDlg);

#ifdef __SOMIDL__
  implementation {

    releaseorder: xwpAddMouseMovementPage,
                  xwpAddAnimatedMousePointerPage;

    /*
     * Class Modifiers:
     *
     */

    externalprefix = xms_;
    externalstem = xms;
    majorversion = 1;
    minorversion = 1;
    filestem = xwpmouse;           //# specifies the filestem for sc-generated files
    metaclass = M_XWPMouse;
    dllname = "xfldr.dll";
    callstyle = oidl;           //# forget CORBA stuff (*ev and such)

    /*
     * WPMouse methods overridden by XWPMouse:
     *
     */

    wpInitData: override;
    wpUnInitData: override;
    wpSetup: override;

    wpSaveState: override;
    wpRestoreState: override;

    wpAddMouseCometPage: override;
    wpAddMousePtrPage: override;
    wpAddMouseMappingsPage: override;

#ifdef __PRIVATE__

#endif

  }; // implementation
#endif /* __SOMIDL__ */
};

//#
//#
//# Now define Metaclass.
//# ---------------------
//#

interface M_XWPMouse : M_WPMouse
{

#ifdef __SOMIDL__
  implementation {

    /*
     * Class Modifiers:
     *
     */

    externalprefix = xmsM_;
    externalstem = xmsM;
    functionprefix = xmsM_;
    majorversion = 1;
    minorversion = 1;
    filestem = xwpmouse;           //# specifies the filestem for sc-generated files
    dllname = "xfldr.dll";
    callstyle = oidl;

    /*
     * Internal instance variables:
     *
     */

    /*
     * M_WPMouse methods overridden by M_XWPMouse:
     *
     */

    wpclsInitData: override;
        /*@@ wpclsInitData:
           initialize XWPMouse class data. */

    wpclsQuerySettingsPageSize: override;
        /*@@ wpclsQuerySettingsPageSize:
           this WPObject class method should return the
           size of the largest settings page in dialog
           units; if a settings notebook is initially
           opened, i.e. no window pos has been stored
           yet, the WPS will use this size, to avoid
           truncated settings pages. */

  };
#endif /* __SOMIDL__ */
};


