
/*
 * xwppgm.idl:
 *      SOM interface description file for the following
 *      XWorkplace classes (in this order):
 *          XWPProgram
 *      and the respective metaclasses.
 *
 *      See src\classes\xwppgm.c for details.
 *
 *      Copyright (C) 2001 Ulrich M”ller.
 *      This file is part of the XWorkplace source package.
 *      XWorkplace is free software; you can redistribute it and/or modify
 *      it under the terms of the GNU General Public License as published
 *      by the Free Software Foundation, in version 2 as it comes in the
 *      "COPYING" file of the XWorkplace main distribution.
 *      This program is distributed in the hope that it will be useful,
 *      but WITHOUT ANY WARRANTY; without even the implied warranty of
 *      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *      GNU General Public License for more details.
 */

#include <wppgm.idl>         // this is SOM for WPProgram

/*
   CLASS: XWPProgram

   CLASS HIERARCHY:

       SOMObject
         ÀÄÄ WPObject = XFldObject
               ÀÄÄ WPAbstract
                     ÀÄÄ WPProgram
                           ÀÄÄ XWPProgram
*/

interface M_XWPProgram;            // Forward Reference to XWPProgram metaclass

interface XWPProgram : WPProgram
{

    /*
     * New instance methods for XWPProgram:
     *
     */

    ULONG xwpAddAssociationsPage(in HWND hwndNotebook);

    BOOL xwpQuerySetup2(in PVOID pstrSetup);

    BOOL xwpNukePhysical();

    BOOL xwpQueryExecutable(in PSZ pszBuffer);

#ifdef __SOMIDL__
  implementation {

    releaseorder: xwpAddAssociationsPage,
                  xwpQuerySetup2,
                  xwpNukePhysical;

    /*
     * Class Modifiers:
     *
     */

    externalprefix = xpg_;
    externalstem = xpg;
    majorversion = 1;
    minorversion = 1;
    filestem = xwppgm;           //# specifies the filestem for sc-generated files
    metaclass = M_XWPProgram;
    dllname = "xfldr.dll";
    callstyle = oidl;            //# forget CORBA stuff (*ev and such)

    /*
     * Internal instance variables for XWPProgram:
     *
     */

    BOOL        fNeedsSetProgIcon;      // flag for WPProgram::wpSetProgIcon

    // pointers into WPProgramFile instance data
    /* PVOID       pvpszEnvironment;       // pointer to a PSZ containing a
                                        // string array with the program's
                                        // environment (last string is terminated
                                        // with two null bytes)

    PVOID       pSWPInitial;            // pointer to SWP struct

    PULONG      pulExecutableHandle;    // 16-bit file-system handle for executable;
                                        //     0xFFFF marks a "*" executable (cmdline)
    PULONG      pulStartupDirHandle;    // 16-bit file-system handle for startup dir
    PPROGTYPE   pProgType;              // prog type and visibility flag; two ULONGs!
       */

    // program data
    PROGTYPE    ProgType;

    USHORT      usExecutableHandle;
    PSZ         pszExecutable;          // only used if the user did not specify a
                                        // executable that could be resolved to
                                        // the executable fshandle above (e.g. an
                                        // executable on the PATH)

    PSZ         pszParameters;          // parameters string

    USHORT      usStartupDirHandle;

    PSZ         pszEnvironment;
    SWP         swpInitial;

    /*
     * WPProgram methods overridden by XWPProgram:
     *
     */

    wpInitData: override;
    wpUnInitData: override;

    //# wpSetup: override;                  not needed, this properly calls the methods

    wpSaveState: override;
    wpRestoreState: override;

    wpRestoreData: override;

    wpObjectReady: override;

    wpOpen: override;

    wpQueryIcon: override;
    wpSetProgIcon: override;
    wpQueryIconData: override;
    wpSetIconData: override;

    wpSetAssociationType: override;

    wpMoveObject: override;
    wpCopyObject: override;

    wpQueryProgDetails: override;
    wpSetProgDetails: override;

    //# wpDestroyObject: override;
    //# can't override this, add xwpNukeObject instead

    wpAddProgramPage: override;
    wpAddProgramSessionPage: override;
    wpAddProgramAssociationPage: override;

#ifdef __PRIVATE__

#endif

  }; // implementation
#endif /* __SOMIDL__ */
};

//#
//#
//# Now define Metaclass.
//# ---------------------
//#

interface M_XWPProgram : M_WPProgram
{

    /*
     * New class methods for M_XWPProgram:
     *
     */

#ifdef __SOMIDL__
  implementation {

    /*
     * Class Modifiers:
     *
     */

    externalprefix = xpgM_;
    externalstem = xpgM;
    functionprefix = xpgM_;
    majorversion = 1;
    minorversion = 1;
    filestem = xwppgm;           //# specifies the filestem for sc-generated files
    dllname = "xfldr.dll";
    callstyle = oidl;

    /*
     * Internal class variables for M_XWPProgram:
     *
     */

    /*
     * M_WPProgram methods overridden by M_XWPProgram:
     *
     */

    wpclsInitData: override;
  };
#endif /* __SOMIDL__ */
};


